[ids]
# Łap wszystko co Logitech USB Receiver
046d:c548

[main]
# Lewa strona: Command <-> Control
#leftmeta = leftcontrol
#leftcontrol = leftmeta

# Prawa strona: Command -> AltGr, Alt -> Super
rightmeta = rightalt
rightalt = rightmeta

# Zamiana: klawisz <> obok Z <-> klawisz grave/tilde
102nd = grave
grave = 102nd

